name: Evanesce
version: ${version}
main: com.github.dwesolowski.evanesce.Evanesce
api-version: 1.13

commands:
  vanish:
    usage: /<command>
    description: "Show / Hide yourself from other online players!"
    permission: evanesce.vanish
# Allowed defaults are: true, false, op, not op
# If nodes does not exist, permission defaults to op.
permissions:
  evanesce.vanish:
    description: "Gives access to the evanesce command."
    default: op